/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DAOVoting__factory } from "./DAOVoting__factory";
export { VotingToken__factory } from "./VotingToken__factory";
